# Generated by Django 5.2.15 on 2026-07-01 01:36

from django.db import migrations


def create_roles(apps, schema_editor):

    Role = apps.get_model("accounts", "Role")

    roles = [
        "Super Administrateur",
        "Administrateur",
        "Responsable",
        "Employé",
        "Consultation",
    ]

    for role in roles:
        Role.objects.get_or_create(
            name=role
        )


def delete_roles(apps, schema_editor):

    Role = apps.get_model("accounts", "Role")

    Role.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_permission_role_permissions'),
    ]

    operations = [
        migrations.RunPython(
            create_roles,
            delete_roles,
        ),
    ]