# Generated by Django 5.2.15 on 2026-07-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_create_default_roles_permissions"),
    ]

    operations = [

        migrations.AlterModelOptions(
            name="permission",
            options={
                "ordering": ["module", "resource", "action"],
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
            },
        ),

        migrations.AddField(
            model_name="permission",
            name="resource",
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                verbose_name="Ressource",
            ),
        ),

        migrations.AddField(
            model_name="permission",
            name="action",
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                verbose_name="Action",
            ),
        ),

        migrations.AlterField(
            model_name="permission",
            name="module",
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                verbose_name="Module",
            ),
        ),

        migrations.AlterField(
            model_name="permission",
            name="is_active",
            field=models.BooleanField(
                default=True,
                verbose_name="Actif",
            ),
        ),

        migrations.RemoveField(
            model_name="permission",
            name="code",
        ),

        migrations.AlterUniqueTogether(
            name="permission",
            unique_together={
                ("module", "resource", "action"),
            },
        ),
    ]