# Generated by Django 5.2.15 on 2026-07-01 01:48

from django.db import migrations

def create_permissions(apps, schema_editor):

    Permission = apps.get_model("accounts", "Permission")

    permissions = [

        # ==========================
        # ACCOUNTS - USERS
        # ==========================

        {
            "module": "accounts",
            "resource": "user",
            "action": "view",
            "name": "Voir les utilisateurs",
        },
        {
            "module": "accounts",
            "resource": "user",
            "action": "create",
            "name": "Créer un utilisateur",
        },
        {
            "module": "accounts",
            "resource": "user",
            "action": "update",
            "name": "Modifier un utilisateur",
        },
        {
            "module": "accounts",
            "resource": "user",
            "action": "delete",
            "name": "Supprimer un utilisateur",
        },

        # ==========================
        # ACCOUNTS - ROLES
        # ==========================

        {
            "module": "accounts",
            "resource": "role",
            "action": "view",
            "name": "Voir les rôles",
        },
        {
            "module": "accounts",
            "resource": "role",
            "action": "create",
            "name": "Créer un rôle",
        },
        {
            "module": "accounts",
            "resource": "role",
            "action": "update",
            "name": "Modifier un rôle",
        },
        {
            "module": "accounts",
            "resource": "role",
            "action": "delete",
            "name": "Supprimer un rôle",
        },

        # ==========================
        # DASHBOARD
        # ==========================

        {
            "module": "dashboard",
            "resource": "dashboard",
            "action": "view",
            "name": "Accéder au tableau de bord",
        },

    ]

    for permission in permissions:

        Permission.objects.get_or_create(
            module=permission["module"],
            resource=permission["resource"],
            action=permission["action"],
            defaults={
                "name": permission["name"],
            },
        )


def delete_permissions(apps, schema_editor):

    Permission = apps.get_model("accounts", "Permission")

    Permission.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_create_default_roles_permissions'),
    ]

    operations = [
        migrations.RunPython(
            create_permissions,
            delete_permissions,
        ),
    ]
