# Generated by Django 5.2.15 on 2026-08-05 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name="Nom d'utilisateur")),
                ('login_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de connexion')),
                ('logout_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de déconnexion')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Navigateur')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Système')),
                ('device', models.CharField(blank=True, max_length=100, verbose_name='Appareil')),
                ('status', models.CharField(choices=[('SUCCESS', 'Connexion réussie'), ('FAILED', 'Connexion échouée'), ('LOGOUT', 'Déconnexion')], default='SUCCESS', max_length=20)),
                ('failure_reason', models.TextField(blank=True, verbose_name="Motif de l'échec")),
                ('session_duration', models.PositiveIntegerField(default=0, verbose_name='Durée (secondes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_histories', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de connexion',
                'verbose_name_plural': 'Historiques de connexion',
                'db_table': 'login_history',
                'ordering': ['-login_at'],
            },
        ),
    ]
