# Generated by Django 5.2.15 on 2026-08-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='logout_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Déconnexion'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='session_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Durée de session'),
        ),
    ]
